### PR TITLE
Dead letter queue framework

### PR DESCRIPTION
**Pull request by zebehringer**
## Why?
* [MOB-1094](): WMS wants to view messages in the dead letter queue to figure out why they are invalid

## What changed?
- [x] Added a class to expose our common Message Bus operations
- [x] Added a class to expose dead letter queue extraction operations

### CODE REVIEW

**Comment by branchvincent** [comment]
This seems specific to WMS, I'm assuming the intention was for this to live in https://bitbucket.org/lineagenext/wms-etl/src/master/cli/wms_etl/

@kkikendall @jrcrawfo is that right?

**Comment by zebehringer** [comment]
@branchvincent yes, but this portion of it is common functionality, at least in my mind. This will be exposed as a CLI command in the wms-etl project, with their environment-specific configurations.
FYI all - this PR is just a draft at the moment

**Comment by zebehringer** [comment]
These features are exposed in WMS-ETL https://bitbucket.org/lineagenext/wms-etl/branch/feature/MOB-1094_dlq_consumer

**Comment by mgagliardo91** [comment]
@zebehringer I would also agree it may be worth just putting it in the wms cli, only because my hopes are that MB as a whole goes away, so it wouldn't be used in a more generic way. idk @kkikendall wdyt?

Nice work on the impl though!

**Pull request closed without merging**
